apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: buildpack-admission
    path: deployment.patch.yaml
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: buildpack-admission
    path: webhook.patch.yaml
images:
  - name: buildpack-admission
    newTag: latest
